services:
  db:
    image: 'postgres:15.3-alpine'
    environment:
      POSTGRES_USER: *postgres user name*
      POSTGRES_PASSWORD: *postgres user password*
      POSTGRES_DB: *postgres db name*
      PGDATA: /var/lib/postgresql/data
    volumes:
      - *docker volume name*:/var/lib/postgresql
    restart: on-failure
    ports:
      - '5730:5432' # external port (change on your own if need):internal default port(don't change it)
  bot:
    build: .
    environment:
      DB_HOST: db # internal network name (don't change)
      DB_NAME: *postgres db name*
      DB_PASS: *postgres user password*
      DB_USER: *postgres user name*
      TOKEN: *bot token (str)*
    restart: always
    links:
      - db
    depends_on:
      - db

volumes:
  *docker volume name*:
    external: true